development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:bc71b87a3da8a649d8846715d08d7c86@koi.redistogo.com:11085/
  channel_prefix: smack-api_production
